In [1]:
import pandas as pd

data_root = "./"
av_df = pd.read_csv(data_root + "av_data.csv")

In [2]:
av_df

,participant_id,media_id,media_modality,arousal,valence,timestamp,overlay_type,seq
0,4,1cQh1ccqu8M,muted_video,0.000000,0.000000,0.5,false,0
1,4,1cQh1ccqu8M,muted_video,0.000000,0.000000,1.0,false,1
2,4,1cQh1ccqu8M,muted_video,0.000000,0.000000,1.5,false,2
3,4,1cQh1ccqu8M,muted_video,0.000000,0.000000,2.0,false,3
4,4,1cQh1ccqu8M,muted_video,0.000000,0.000000,2.5,false,4
...,...,...,...,...,...,...,...,...
179322,11,cSnkWzZ7ZAA,muted_video,0.686957,0.269565,58.0,false,115
179323,11,cSnkWzZ7ZAA,muted_video,0.686957,0.269565,58.5,false,116
179324,11,cSnkWzZ7ZAA,muted_video,0.686957,0.269565,59.0,false,117
179325,11,cSnkWzZ7ZAA,muted_video,0.686957,0.269565,59.5,false,118
179326,11,cSnkWzZ7ZAA,muted_video,0.678261,0.269565,60.0,false,119

In [6]:
av_df = av_df[av_df['media_modality'] == 'music']
av_df

,participant_id,media_id,media_modality,arousal,valence,timestamp,overlay_type,seq
2621,13,OMOGaugKpzs,music,0.000000,0.000000,0.0,irrelevant,0
2622,13,OMOGaugKpzs,music,0.026087,0.000000,0.7,irrelevant,1
2623,13,OMOGaugKpzs,music,0.026087,0.000000,1.0,irrelevant,2
2624,13,OMOGaugKpzs,music,0.026087,0.000000,1.5,irrelevant,3
2625,13,OMOGaugKpzs,music,0.026087,0.000000,2.0,irrelevant,4
...,...,...,...,...,...,...,...,...
178962,11,tg00YEETFzg,music,0.513043,-0.078261,57.9,irrelevant,115
178963,11,tg00YEETFzg,music,0.547826,-0.008696,58.4,irrelevant,116
178964,11,tg00YEETFzg,music,0.556522,-0.008696,58.9,irrelevant,117
178965,11,tg00YEETFzg,music,0.573913,-0.008696,59.4,irrelevant,118
178966,11,tg00YEETFzg,music,0.591304,-0.017391,59.9,irrelevant,119

In [10]:
uniq = av_df['media_id'].unique()
len(uniq)
uniq

array(['OMOGaugKpzs', '9bZkp7q19f0', 'yyDUC1LUXSU', 'cSnkWzZ7ZAA',
       'ebXbLfLACGM', '4JipHEz53sU', 'J9NQFACZYEU', 'KlyXNRrsk4A', 'Dsp',
       'J3UjJ4wKLkg', 'nCkpzqqog4k', 'S9bCLPwzSC0', 'Ahha3Cqe',
       'CevxZvSJLk8', 'bjgFH01k0gU', 'kffacxfA7G4', 'btPJPFnesV4',
       '8xg3vE8Ie', 'dvgZkm1xWPE', 'n4RjJKxsamQ', 'vNoKguSdy4Y',
       'VPRjCeoBqrI', 'E8gmARGvPlI', 'o3mP3mJDL2k', '8SbUC-UaAxE', 'hT',
       'ASO', 'tg00YEETFzg', 'RB-RcX5DS5A', 'Zi', 'EkHTsc9PU2A',
       'IcrbM1l', 'LjhCEhWiKXk', 'j5-yKhDd64s', 'kTHNpusq654',
       'QGJuMBdaqIw', 'U0CGsw6h60k', 'LrUvu1mlWco', 'OZLUa8JUR18',
       'AtKZKl7Bgu0', 'QJO3ROT-A4E', 'k0BWlvnBmIE', 'e-fA-gBCkj0',
       '7RMQksXpQSk', 'weRHyjj34ZE', 'My2FRPA3Gf8', 'iS1g8G',
       'lDK9QqIzhwk', 'wyx6JDQCslE', '47dtFZ8CFo8', 'KRaWnd3LJfs',
       'rtOvBOTyX00', '1cQh1ccqu8M', 'W-TE', '8WYHDfJDPDc', 'yd8jh9QYfEs',
       'fV4DiAyExN0', '3YxaaGgTQYM', 'kXYiU', 'JRfuAukYTKg',
       '2vjPBrBU-TM', 'YxIiPLVR6NA', '6Ejga4kJUts', 'u0pmV7GoTjc',
       '8UVNT4wvIGY', 'XjwZAa2EjKA', 'bnVUHWCynig', 't5Sd5c4o9UM',
       'mWRsgZuwf', 'ovdm2yX4MA', 'M11SvDtPBhA', 'WA4iX5D9Z64',
       'PIh2xe4jnpk', 'OpQFFLBMEPI', 'SmM0653YvXU', 'Bg59q4puhmg',
       'fWNaR-rxAic', '3O1', 'o', 'rYEDA3JcQqw', 'qpgTC9MDx1o'],
      dtype=object)

In [11]:

urls = pd.read_csv(data_root + "video_urls.csv")

In [12]:
urls

       video_id
0   lDK9QqIzhwk
1   4JipHEz53sU
2   j5-yKhDd64s
3   J9NQFACZYEU
4   t5Sd5c4o9UM
..          ...
76  8SbUC-UaAxE
77  WA4iX5D9Z64
78  bjgFH01k0gU
79  3O1_3zBUKM8
80  8WYHDfJDPDc

[81 rows x 1 columns]

In [15]:
import numpy as np
np.array(av_df['timestamp'])

array([ 0. ,  0.7,  1. , ..., 58.9, 59.4, 59.9])